name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - dev
      - stage
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Pre-Release (dev)
        if: ${{ github.ref_name == 'dev' || github.ref_name == 'stage' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run pre-release

      - name: Release
        if: ${{ github.ref_name == 'main' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release

      - name: Cleanup old dev/stage tags
        if: success()
        run: |
          git fetch --tags && \
          for p in dev stage; do \
            git tag -l "*-$p.*" | sort -V | head -n -1 | \
              xargs -r -n1 -I{} sh -c 'git push origin --delete "{}" && git tag -d "{}"'; \
          done
